// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1mmyDAFt9mKIjj6n4dis3tDXkeVffc4',
    appId: '1:180956976970:android:b5c8ea99518c0abe55d3b3',
    messagingSenderId: '180956976970',
    projectId: 'money-tracker-af62e',
    databaseURL: 'https://money-tracker-af62e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-tracker-af62e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLLJrOkbCTVLDH4CNuDLRnC9QaAzV-_tU',
    appId: '1:180956976970:ios:a9891d86cffd69cd55d3b3',
    messagingSenderId: '180956976970',
    projectId: 'money-tracker-af62e',
    databaseURL: 'https://money-tracker-af62e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'money-tracker-af62e.firebasestorage.app',
    iosBundleId: 'com.example.money',
  );
}
